---
# Layout of the physical device
MacroLayout:
  SizeX: 3
  SizeY: 4
  # Size of the GUI
  Width: 300
  Height: 200
SerialDevice:
  # Serial Port name
  PortName: COM7
  BaudRate: 9600
  # Timeout: 20ms
Delay: 60ms # Delay for ShortCuts
# List of Macros to
Macros:
  1:
    Name: nt
    Actions:
      - PressKey: VK_ENTER
      - SendString: nt
      - PressKey: VK_ENTER
  2:
    Name: nice
    Actions:
      - Shortcut: ENTER
      - SendString: nice
      - Shortcut: ENTER
  # Position on display
  3:
    # Text on button
    Name: Open Task Mgr
    # List of stuff to do
    Actions:
      # FuncName: "param"
      # - TaskMgr: ""
      - Shortcut: "CTRL+SHIFT+ESC"
  4:
    Name: gg
    Actions:
      - Shortcut: "SHIFT+ENTER"
      - SendString: gg
      - Shortcut: "ENTER"
  5:
    Name: ggwp
    Actions:
      - Shortcut: "SHIFT+ENTER"
      - SendString: ggwp
      - Shortcut: "ENTER"
  6:
    Name: ggez
    Actions:
      - Shortcut: "SHIFT+ENTER"
      - SendString: ggez
      - Shortcut: "ENTER"
  7:
    Name: surf reset all
    Actions:
      - Shortcut: "ENTER"
      - Delay: 100ms
      - SendString: "/r"
      - Delay: 100ms
      - Shortcut: "ENTER"
  8:
    Name: surf reset stage
    Actions:
      - Shortcut: "ENTER"
      - Delay: 100ms
      - SendString: "/rs"
      - Delay: 100ms
      - Shortcut: "ENTER"
  9:
    Name: startup folder
    Actions:
      - Shortcut: "SUPER+R"
      - Delay: 100ms
      - SendString: "shell:startup"
      - Delay: 100ms
      - Shortcut: "ENTER"
  # Button 10
  10:
    Name: Skip song
    Actions:
      - PressKey: VK_MEDIA_NEXT_TRACK
