---
# Layout of the physical device
MacroLayout:
  SizeX: 3
  SizeY: 3
  # Size of the GUI
  Width: 300
  Height: 200
SerialDevice:
  # Serial Port name
  PortName: COM7
  BaudRate: 9600
  # Timeout: 20ms
# List of Macros to
Macros:
  # Position on display
  1:
    # Text on button
    Name: Open Task Mgr
    # List of stuff to do
    Actions:
      # FuncName: "param"
      # - TaskMgr: ""
      - Shortcut: "CTRL+SHIFT+ESC"
  2:
    Name: nt
    Actions:
      - PressKey: VK_ENTER
      - SendString: nt
      - PressKey: VK_ENTER
  3:
    Name: nice
    Actions:
      - PressKey: VK_ENTER
      - SendString: nice
      - PressKey: VK_ENTER
  4:
    Name: gg
    Actions:
      - Shortcut: "SHIFT+ENTER"
      - SendString: gg
      - Shortcut: "ENTER"
  # Button 10
  10:
    Name: Skip song
    Actions:
      - PressKey: VK_MEDIA_NEXT_TRACK
Delay: 20ms
