---
# Layout of the physical device
MacroLayout:
  # Rows/Cols of buttons
  SizeX: 3
  SizeY: 4
  # Size of the GUI
  Width: 300
  Height: 200
SerialDevice:
  # Serial Port name
  PortName: COM7
  BaudRate: 9600
Delay: 125ms # Delay for Shortcuts
# List of Macros
Macros:
  # Position on display
  1:
    # Text on button
    Name: nt
    # List of stuff to do
    Actions:
      # FuncName: param
      - PressRelease: enter
      - SendText: nt
      - PressRelease: enter
  2:
    Name: nice
    Actions:
      - PressRelease: enter
      - SendText: nice
      - PressRelease: enter
  3:
    Name: Open Task Mgr
    Actions:
      - Shortcut: CTRL+SHIFT+ESC
  4:
    Name: gg
    Actions:
      - Shortcut: SHIFT+ENTER
      - SendText: gg
      - PressRelease: enter
  5:
    Name: ggwp
    Actions:
      - Shortcut: SHIFT+ENTER
      - SendText: ggwp
      - PressRelease: enter
  6:
    Name: ggez
    Actions:
      - Shortcut: SHIFT+ENTER
      - SendText: ggez
      - PressRelease: enter
  7:
    Name: surf reset all
    Actions:
      - PressRelease: enter
      - Delay: 100ms
      - SendText: "/r"
      - Delay: 100ms
      - PressRelease: enter
  8:
    Name: surf reset stage
    Actions:
      - PressRelease: enter
      - Delay: 100ms
      - SendText: "/rs"
      - Delay: 100ms
      - PressRelease: enter
  9:
    Name: Spam Click
    Actions:
      - Repeat: LMB+100ms
  10:
    Name: Skip song
    Actions:
      - PressRelease: audio_next
  11:
    Name: startup folder
    Actions:
      - Shortcut: cmd+r
      - Delay: 100ms
      - SendText: "shell:startup"
      - Delay: 100ms
      - PressRelease: enter
