---
# Layout of the physical device
MacroLayout:
  SizeX: 3
  SizeY: 3
  # Size of the GUI
  Width: 300
  Height: 200
SerialDevice:
  # Serial Port name
  PortName: COM7
  BaudRate: 9600
  # Timeout: 20ms
# List of Macros to
Macros:
  # Position on display
  1:
    # Text on button
    Name: Open Task Mgr
    # List of stuff to do
    Actions:
      # FuncName: "param"
      - TaskMgr: ""
  2:
    Name: nt
    Actions:
      # FuncName: "param"
      - Shortcut: ""
  3:
    Name: gg
    Actions:
      # FuncName: "param"
      - PressKey: VK_ENTER
      - Delay: 100ms
      - SendString: "gg"
      - Delay: 100ms
      - PressKey: VK_ENTER
      # - Shortcut: "SHIFT+ENTER"
      # - Shortcut: "ENTER"
  # Button 10
  10:
    Name: Skip song
    Actions:
      - PressKey: VK_MEDIA_NEXT_TRACK
Delay: 20ms
