---
# Layout of the physical device
MacroLayout:
  SizeX: 3
  SizeY: 3
  # Size of the GUI
  Width: 500
  Height: 400
SerialDevice:
  # Serial Port name
  PortName: COM7
  BaudRate: 9600
  # Timeout: 20ms
# List of Macros to
Macros:
  # Text on button
  - Name: Open Task Mgr
    # Position on display
    ActionID: 1
    # List of stuff to do
    Actions:
      - TaskMgr: ""
  - Name: Skip song
    ActionID: 10
    Actions:
      - PressKey: VK_MEDIA_NEXT_TRACK
Delay: 20ms
