name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup fyne
        run: |
          sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev bc
          go install -tags k8s github.com/fyne-io/fyne-cross@latest

      - name: run tests
      - run: go test -v -coverprofile=profile.cov ./...

      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          go_version: 1.22
          dest: build
          prefix: myapp
          targets: windows/amd64,linux/amd64
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true

      - name: Update coverage
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          set -e
          go test -tags ci -covermode=atomic -coverprofile=coverage.out ./...
          coverage=`go tool cover -func coverage.out | grep total | tr -s '\t' | cut -f 3 | grep -o '[^%]*'`
          if (( $(echo "$coverage < 85" | bc) )); then echo "Test coverage lowered"; exit 1; fi

      
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
