---
MacroLayout:
  SizeX: 2
  SizeY: 2
  Width: 300
  Height: 300
SerialDevice:
  PortName: COM1
  BaudRate: 9600
Delay: 125ms
GUIMode: NORMAL
Macros:
  1:
    Name: first
    Actions:
      - SendText: first
  2:
    Name: second
    Actions:
      - SendText: second
  3:
    Name: third
    Actions:
      - SendText: third
