---
Metadata:
  Columns: 2
  SerialPortName: "COM1"
  SerialBaudRate: 9600
  Delay: 125ms
  GUIMode: GUIOnly
Macros:
  - Name: Undo
    Actions:
      - FuncName: Shortcut
        FuncParam: CTRL+Z
  - Name: gg
    Actions:
      - FuncName: PressRelease
        FuncParam: Enter
      - FuncName: Delay
        FuncParam: 100ms
      - FuncName: SendText
        FuncParam: gg
      - FuncName: PressRelease
        FuncParam: Enter
  - Name: close game
    Actions:
      - FuncName: Shortcut
        FuncParam: ALT+F4